services:
  postgres:
    image: postgres:18
    container_name: secure_chat_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: public
    ports:
      - "5432:5432"
    volumes:
      - secure_chat_pgdata:/var/lib/postgresql

volumes:
  secure_chat_pgdata: